import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/ClientPrvovider";
import UserContext from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Latest FullStack NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <UserContext>{children}</UserContext>
        </ClientProvider>
      </body>
    </html>
  );
}
